# IMPORTANT:
# 1. The Server URL must include the scheme (e.g. https://app.remotely.one).

# 2. The Server Runtime Identifier determines the target operating system
# for which to build the server.  The default "linux-x64" will usually work
# for most Linux-based operating systems.  You can see a full list at
# https://docs.microsoft.com/en-us/dotnet/core/rid-catalog.

# 2. You'll want to keep your fork updated so you can build the latest
# changes.  On the GitHub page for your repo, you'll see a message that says,
# "This branch is ## commits behind lucent-sea:master."
#
# Click the "Pull request" link next to it.
#
# On the next page click the "switching the base" link.  Now it's pulling from
# my repo into yours.  Create and complete the pull request to update your repo.
#
# Once your branch has been updated, you can run this workflow again
# to build the latest version.

name: Build_Arm64

on:
  workflow_dispatch:
    inputs:
      serverUrl:
        description: 'Server URL'     
        required: true
      rid:
        description: 'Server Runtime Identifier'     
        required: false
        default: "linux-x64"

jobs:

  build-arm64:
  
    runs-on: macos-10.15
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1.8.0
        
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5

      - name: Set current version
        shell: pwsh
        run: |
          $VersionString = git show -s --format=%ci
          $VersionDate = [DateTimeOffset]::Parse($VersionString)

          $Year = $VersionDate.Year.ToString()
          $Month = $VersionDate.Month.ToString().PadLeft(2, "0")
          $Day = $VersionDate.Day.ToString().PadLeft(2, "0")
          $Hour = $VersionDate.Hour.ToString().PadLeft(2, "0")
          $Minute = $VersionDate.Minute.ToString().PadLeft(2, "0")
          $CurrentVersion = "$Year.$Month.$Day.$Hour$Minute"

          echo "CurrentVersion=$CurrentVersion" >> $env:GITHUB_ENV

          Write-Host "Setting current version to $CurrentVersion."

      - name: Publish Arm64 Agent
        shell: pwsh
        run: |
          $VersionString = git show -s --format=%ci
          $VersionDate = [DateTimeOffset]::Parse($VersionString)

          $Year = $VersionDate.Year.ToString()
          $Month = $VersionDate.Month.ToString().PadLeft(2, "0")
          $Day = $VersionDate.Day.ToString().PadLeft(2, "0")
          $Hour = $VersionDate.Hour.ToString().PadLeft(2, "0")
          $Minute = $VersionDate.Minute.ToString().PadLeft(2, "0")
          $CurrentVersion = "$Year.$Month.$Day.$Hour$Minute"
          
          Write-Host "Publishing agent with version $CurrentVersion"
          dotnet publish /p:Version=$CurrentVersion /p:FileVersion=$CurrentVersion --runtime linux-arm --configuration Release --output "./Agent/bin/publish/" "./Agent/"
          Compress-Archive -Path "./Agent/bin/publish/*" -DestinationPath "./Agent/bin/Remotely-Arm64.zip" -Force

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./Agent/bin/Remotely-Arm64.zip
          name: Arm-Agent-x64
     
 